# Generated by Django 4.1.7 on 2023-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senoves_civil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilizacijos',
            options={'ordering': ['title'], 'verbose_name': 'Senoves Civilizacijos', 'verbose_name_plural': 'Senoves Civilizacijos'},
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='content',
            field=models.TextField(blank=True, verbose_name='Turinys'),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='region',
            field=models.CharField(max_length=250, verbose_name='Regionas'),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
    ]
