# Generated by Django 4.1.7 on 2023-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senoves_civil', '0002_alter_civilizacijos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50, verbose_name='Nikas')),
                ('title', models.CharField(max_length=100, verbose_name='Komentaro pavadinimas')),
                ('content', models.TextField(verbose_name='Komentaras')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.AlterModelOptions(
            name='civilizacijos',
            options={'verbose_name': 'Senoves Civilizacijos', 'verbose_name_plural': 'Civilizacijos'},
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='region',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='civilizacijos',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
